name: Check Docker Compose

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" \
            -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: List files in the current directory
        run: ls -al

      - name: Create .env from .env.example
        run: cp .env.example .env

      - name: Check Docker Compose config
        run: docker-compose --env-file .env -f docker-compose.yml config
